version: 2.1

orbs:
#  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
